# SPDX-License-Identifier: GPL-2.0

MTK_COMBO_CHIP			:= MT7902
CONFIG_MTK_COMBO_WIFI_HIF	:= sdio
WM_RAM				:= alps
BRANCH				:= android12-5.10
CONFIG_GKI_SUPPORT		:= y
DRIVER_BUILD_DATE		:= $(KERNELRELEASE)

ccflags-y			+= -Wno-\#pragma-messages

MODULE_NAME			:= wlan_mt7902_sdio
MODULE_NAME_PREALLOC		:= $(MODULE_NAME)_prealloc
MODULE_NAME_RESET		:= $(MODULE_NAME)_reset

CONFIG_MTK_PREALLOC_MEMORY	:= $(if $(CONFIG_MTK_WLAN_GEN4_MT79XX_PREALLOC),y,n)
CONFIG_BUILD_MTPREALLOC		:= $(CONFIG_MTK_PREALLOC_MEMORY)
CONFIG_CHIP_RESET_KO_SUPPORT	:= n
CONFIG_BUILD_RESETKO		:= n
CONFIG_CHIP_RESET_LEGACY_KO	:= $(if $(CONFIG_MTK_WLAN_GEN4_MT79XX_RESET),y,n)

ccflags-y			+= -I$(srctree)/$(src)/reset/include

ifeq ($(CONFIG_MTK_WLAN_GEN4_MT79XX_RESET),y)
obj-m				+= $(MODULE_NAME_RESET).o
$(MODULE_NAME_RESET)-y		:= reset/whole_chip_reset.o
endif

include $(srctree)/$(src)/Makefile
